module test

import novah.vector as V

foreign import type java.lang.RuntimeException
foreign import new RuntimeException(String) as newRte
foreign import java.util.Arrays:toString(Array) as toStringArr

toStr : Array a -> String
toStr arr = toStringArr (unsafeCast arr)

pub
main : Array String -> Unit
main _ = do
  let arr = arrayOf [4, 5, 6, 7]
  let printArr = toStr >> println
  arraySet 2 99 arr
  format "these options are equal: %s" [Some 3 == Some 4] |> println
  None ?: 3 |> println
  #{1, 2, 3} ++ #{5, 6, 7} |> println
  printArr arr
  println (show (Err 45 : Result Int Int))
  println (V.nth 8L [56, 777, 1237, 12])
  format "some %s once told %s" ["body", "me"] |> println
  [56, 78, 90, 14, 566] |> (_ ! 4L) |> println
  throw (newRte "oops")